import csv
import re
import os
from typing import List, Dict, Any, Optional
from ..models import MigrationResult


class SQLLoaderWriter:
    """
    Generates SQL*Loader shell script with embedded control file and data.
    The target bank can run this script to load data into Oracle database.
    """

    def __init__(self):
        # SQL*Loader type mappings for common Python types
        self._type_mapping = {
            "int": "INTEGER EXTERNAL",
            "float": "DECIMAL EXTERNAL",
            "str": "CHAR",
            "bool": "CHAR(1)",
            "datetime": "DATE 'YYYY-MM-DD HH24:MI:SS'",
            "date": "DATE 'YYYY-MM-DD'",
        }

    def _detect_column_type(self, value: Any) -> str:
        """Detect appropriate SQL*Loader type for a value."""
        if value is None or value == "":
            return "CHAR(100)"

        if isinstance(value, bool):
            return "CHAR(1)"

        if isinstance(value, int):
            return "INTEGER EXTERNAL"

        if isinstance(value, float):
            return "DECIMAL EXTERNAL"

        if isinstance(value, str):
            # Try to detect if it's a date
            date_patterns = [
                r"^\d{4}-\d{2}-\d{2}$",
                r"^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}$",
                r"^\d{2}/\d{2}/\d{4}$",
            ]
            for pattern in date_patterns:
                if re.match(pattern, value):
                    return "DATE 'YYYY-MM-DD HH24:MI:SS'"

        # Default to CHAR with length based on string length
        str_len = len(str(value))
        if str_len < 50:
            return f"CHAR({max(str_len, 50)})"
        elif str_len < 255:
            return "CHAR(255)"
        elif str_len < 1000:
            return "CHAR(1000)"
        else:
            return "CHAR(4000)"

    def _sanitize_table_name(self, filename: str) -> str:
        """Generate a valid Oracle table name from filename."""
        # Remove extension and special characters
        name = os.path.splitext(filename)[0]
        # Replace special chars with underscore
        name = re.sub(r"[^a-zA-Z0-9_]", "_", name)
        # Ensure it starts with letter
        if name and name[0].isdigit():
            name = "T_" + name
        # Convert to uppercase (Oracle convention)
        name = name.upper()
        # Limit to 30 chars (Oracle identifier limit)
        name = name[:30]
        # Ensure not empty
        if not name:
            name = "BANK_MIGRATION_DATA"
        return name

    def _escape_csv_field(self, field: Any) -> str:
        """Escape a field value for CSV in SQL*Loader."""
        if field is None:
            return ""

        value = str(field)

        # Check if field needs quoting (contains comma, quote, or newline)
        if any(char in value for char in [",", '"', "\n"]):
            # Escape existing quotes by doubling them
            value = value.replace('"', '""')
            return f'"{value}"'

        return value

    def write(self, result: MigrationResult, output_path: str, source_filename: Optional[str] = "data.csv"):
        """
        Generate SQL*Loader shell script with embedded control file and data.

        Args:
            result: MigrationResult containing records to be loaded
            output_path: Path where the .sh script will be written
            source_filename: Original filename used for table name generation
        """
        if not result.records:
            raise ValueError("No records to generate SQL*Loader script")

        # Generate table name from source filename
        table_name = self._sanitize_table_name(source_filename)

        # Detect column types from first row
        first_row = result.records[0]
        column_defs = []
        for col_name, col_value in first_row.items():
            oracle_type = self._detect_column_type(col_value)
            # Sanitize column name
            col_name_clean = re.sub(r"[^a-zA-Z0-9_]", "_", str(col_name)).upper()
            if not col_name_clean or col_name_clean[0].isdigit():
                col_name_clean = "COL_" + col_name_clean
            col_name_clean = col_name_clean[:30]  # Oracle limit
            column_defs.append(f"  {col_name_clean} {oracle_type}")

        # Build the SQL*Loader script
        script_lines = [
            "#!/bin/bash",
            "#",
            "# SQL*Loader Script for Bank Data Migration",
            "# Generated by UN Wallet Multi-Bank Data Migration Platform",
            "#",
            f"# Source File: {source_filename}",
            f"# Target Table: {table_name}",
            f"# Records: {len(result.records)}",
            "#",
            "# Usage:",
            "#   1. Update database connection below (replace username/password@database)",
            "#   2. Run: bash this_script.sh",
            "#   3. Check log files: migration.log and migration.bad",
            "#",
            "",
            "# ==================== DATABASE CONNECTION ====================",
            "# Update this with your Oracle database connection details",
            "DB_USER=\"your_username\"",
            "DB_PASS=\"your_password\"",
            "DB_CONNECT=\"your_database\"",
            "",
            "# ==================== RUN SQL*LOADER ====================",
            "",
            "sqlldr userid=${DB_USER}/${DB_PASS}@${DB_CONNECT} \\",
            "       control=stdin \\",
            "       log=migration.log \\",
            "       bad=migration.bad \\",
            "       discard=migration.discard <<EOF",
            "",
            "OPTIONS (",
            "    DIRECT=TRUE,",
            "    BINDSIZE=5000000,",
            "    ROWS=1000,",
            "    ERRORS=1000",
            ")",
            "",
            "LOAD DATA",
            "INFILE *",
            f"INTO TABLE {table_name}",
            "TRUNCATE",
            "FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '\"' TRAILING NULLCOLS",
            "(",
            ",\n".join(column_defs),
            ")",
            "",
            "BEGINDATA",
        ]

        # Add CSV data rows
        for record in result.records:
            row_values = [self._escape_csv_field(value) for value in record.values()]
            script_lines.append(",".join(row_values))

        script_lines.extend([
            "EOF",
            "",
            "# ==================== STATUS ====================",
            "echo 'SQL*Loader completed. Check migration.log for details.'",
            "if [ -f migration.bad ]; then",
            "    echo 'Rejected records: ' $(wc -l < migration.bad)",
            "fi",
        ])

        # Write the script
        with open(output_path, "w") as f:
            f.write("\n".join(script_lines))

        # Make script executable
        try:
            os.chmod(output_path, 0o755)
        except Exception:
            pass

        return {
            "script_path": output_path,
            "table_name": table_name,
            "records_count": len(result.records),
            "columns": list(first_row.keys()),
        }
